# Generated by Django 5.1.3 on 2024-11-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
